### ISSUE TITLE
On Android phones, its not working

### ISSUE THREAD

**Issue by yigitersoy87** [Tastenkunst/brfv5-browser#14]
Hi, i have tested png overlay example on various android phones, but not worked. Is there a way to work this on android phones?

**Comment by MarcelKlammer** [comment]
It's working on my Samsung Galaxy S9 without problems. Not quite sure how to help here.

**Comment by yigitersoy87** [comment]
Is this working on your side? https://220volt.com.tr/face

**Comment by MarcelKlammer** [comment]
Yes, loads, tracks... the png file is a bit offset, but working as usual.
Make sure to open the https url every time.

**Comment by yigitersoy87** [comment]
> Yes, loads, tracks... the png file is a bit offset, but working as usual.
> Make sure to open the https url every time.

Thank you Marcel, the problem was about https url, i will add redirect from http to https. Just one last issue and after that everything will be perfect. On laptop its working perfectly but on mobile glasses position is changing, how can i fix this?

https://ibb.co/vVh4HcK  (mobile)
https://ibb.co/yYh2b2L  (laptop)

**Comment by MarcelKlammer** [comment]
Updated the minimal__modules__png_overlay.html example to correctly show the overlay in landscape mode.

**Comment by yigitersoy87** [comment]
Work like a charm! Thank you!
