### ISSUE TITLE
Getting blank image while doing HTMLCanvasElement.toDataURL() on id='__brfv5__image_canvas,__brfv5__texture_canvas,__brfv5__threejs_canvas''

### ISSUE THREAD

**Issue by ankitcsr** [Tastenkunst/brfv5-browser#15]
Hi,
I want to capture image of 3d model in three js model overlay. I tried to convert canvas
(id='__brfv5__image_canvas,__brfv5__texture_canvas,__brfv5__threejs_canvas'') to image (using HTMLCanvasElement.toDataURL()) but I am getting black image.

**Comment by MarcelKlammer** [comment]
I think I had the same issue before.
Try to render the scene explicitly before taking the snapshot.

**Comment by ankitcsr** [comment]
Brf is not initializing, showing error 400 at https://www.beyond-reality-face.com/lc

**Comment by MarcelKlammer** [comment]
Adloid? 

If yes, write me an email please.
If no, which URL?

**Comment by ankitcsr** [comment]
at info@tastenkunst.io ?

**Comment by MarcelKlammer** [comment]
Yes.
