### ISSUE TITLE
Face tracking model?

### ISSUE THREAD

**Issue by Rakeshvcr** [Tastenkunst/brfv5-browser#3]
Hello Sir,

I'm glad to see this excellent repo you have done incredible work here. The face tracking implementation is really fast and smooth. I would like to know what model you are using for face tracking?

**Comment by MarcelKlammer** [comment]
It's a modified version of ERT + an Optical Flow stabilizer.

**Comment by Rakeshvcr** [comment]
Hello sir, I'm working on face landmark detection I'm using mobilenet model from Tensorflow for landmark detection, I'm able to reduce the model size using tensorflow. After you said about ERT model I implemented the model using this github repo [Link](https://github.com/jjrCN/ERT-GBDT_Face_Alignment ). Model is working but the model size is too large, Is there any method  or reference that I can follow to reduce the model size. it would be helpful for my project.

**Comment by MarcelKlammer** [comment]
I'm afraid I can't help you with that problem.
