### ISSUE TITLE
Brv4 im using paid version how can i get brfv5 paid version ?

### ISSUE THREAD

**Issue by kamaldlk** [Tastenkunst/brfv5-browser#4]

**Comment by MarcelKlammer** [comment]
Send me an email please. I can't find you in my mails.

**Comment by wiyatnanto** [comment]
Hello @MarcelKlammer,  I sent you an email to ask about the license, thank you

**Comment by wiyatnanto** [comment]
Hello @kamaldlk, can you give me an idea of the price you have paid? I also want to ask about the price
