### ISSUE TITLE
Can i test brfv5 in codepen? 

### ISSUE THREAD

**Issue by cerberart** [Tastenkunst/brfv5-browser#5]
The question is if there any opportunity to test brfv5 in codepen? I usually make some sketches there and show my team before we decide use it or not.

**Comment by MarcelKlammer** [comment]
I just copy pasted the 'no_modules' minimal example to CodePen:

https://codepen.io/tastenkunst/pen/eYYzVqp

I changed the settings for JavaScript to include the GitHub hosted lib...

And I pointed to loadBRFv5Model method to the GitHub hosted models:

https://tastenkunst.github.io/brfv5-browser/js/brfv5/models/

Seems to work.

**Comment by cerberart** [comment]
Sorry for misunderstanding, the question was whether it legal or not to use it in codepen :) thank you for the answer
