### ISSUE TITLE
cam start and stop not working. when I change glass, I need to stop cam and start. progress not working.  t > = 1 something like that u had conditioned it is not satisfied

### ISSUE THREAD

**Issue by kamaldlk** [Tastenkunst/brfv5-browser#6]
cam start and stop not working. when I change glass, I need to stop cam and start. progress not working. t > = 1 something like that u had conditioned it is not satisfied

**Comment by MarcelKlammer** [comment]
hmm? You might want to point directly to the code in questions, otherwise I can't help much.

**Comment by kamaldlk** [comment]
https://github.com/Tastenkunst/brfv5-browser/blob/master/artov5/brfv5-artov5.min.js

this file
