### ISSUE TITLE
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain"

### ISSUE THREAD

**Issue by kashyap32** [Tastenkunst/brfv5-browser#7]
I started a server with python but I am getting this error.

**Comment by MarcelKlammer** [comment]
Which html file did you load? Sounds like a type="module" is missing in a script tag.

**Comment by kashyap32** [comment]
index.html

**Comment by MarcelKlammer** [comment]
Starting a server using Python like this:

python -m SimpleHTTPServer 8000

works for me.

I'm not sure how I can help you here. Maybe update your python to the latest version?

**Comment by kashyap32** [comment]
SimpleHTTPServer is for python2 and it's deprecated for python version 3.
For python3 it's something like this:-  python -m http.server 8000

**Comment by MarcelKlammer** [comment]
Works as well:

/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -m http.server 8000

**Comment by kashyap32** [comment]
So it's working in egde
![image](https://user-images.githubusercontent.com/11897704/69957645-0cc06800-1529-11ea-95f0-57dce55c35fd.png)

but in chrome I am getting this error -

![image](https://user-images.githubusercontent.com/11897704/69957725-38dbe900-1529-11ea-929a-419468b362db.png)

**Comment by MarcelKlammer** [comment]
Then I guess, that your local server configuration is too old and doesn't know how to deliver javascript modules.
